-- ===========================================================================
-- Business TRIZ Portal  —  Startdaten
--
-- Einspielen nach schema_triz.sql. Lässt sich gefahrlos mehrfach ausführen:
-- Jede Zeile hat einen eindeutigen Schlüssel und INSERT IGNORE übergeht, was
-- schon da ist. Eigene Änderungen an vorhandenen Zeilen bleiben erhalten.
--
-- Enthalten sind:
--   - die Kategorien für Nachrichten und Videos
--   - Nachrichtenquellen für alle im Auftrag genannten Themen und Suchbegriffe
--   - die 39 technischen Parameter (deutsch/russisch)
--   - die 40 innovativen Prinzipien mit Erläuterung und Business-Beispiel
--   - die acht Entwicklungsgesetze technischer Systeme
--   - die Business-TRIZ-Methoden und die Innovations-/Management-Werkzeuge
--   - Praxisbeispiele aus dem Elektrohandwerk
--
-- NICHT enthalten: YouTube-Kanäle und die Widerspruchsmatrix. Beides trägt
-- ein Administrator im Portal selbst ein - siehe TRIZ/ANLEITUNG.md. Erfundene
-- Kanalkennungen und aus dem Gedächtnis gefüllte Matrixfelder wären schlechter
-- als ein leerer Anfang.
-- ===========================================================================

SET NAMES utf8mb4;

-- ---------------------------------------------------------------------------
-- Kategorien: Nachrichten
-- ---------------------------------------------------------------------------
INSERT IGNORE INTO triz_kategorien (bereich, schluessel, name_de, name_ru, sortierung) VALUES
('news','business-triz',   'Business TRIZ',            'Бизнес‑ТРИЗ',                 10),
('news','management-triz', 'Management TRIZ',          'ТРИЗ в управлении',           20),
('news','innovation',      'Innovationsmanagement',    'Управление инновациями',      30),
('news','systemdenken',    'Systemisches Denken',      'Системное мышление',          40),
('news','lean',            'Lean Management',          'Бережливое производство',     50),
('news','prozesse',        'Prozessoptimierung',       'Оптимизация процессов',       60),
('news','unternehmen',     'Unternehmensentwicklung',  'Развитие компании',           70),
('news','strategie',       'Strategisches Management', 'Стратегическое управление',   80),
('news','geschaeftsmodell','Geschäftsmodellinnovation','Инновация бизнес‑модели',     90),
('news','ki-triz',         'KI und TRIZ',              'ИИ и ТРИЗ',                  100),
('news','produktion',      'TRIZ in der Produktion',   'ТРИЗ на производстве',       110),
('news','handwerk',        'TRIZ im Handwerk',         'ТРИЗ в ремесле',             120),
('news','digitalisierung', 'TRIZ und Digitalisierung', 'ТРИЗ и цифровизация',        130);

-- ---------------------------------------------------------------------------
-- Kategorien: Videos
-- ---------------------------------------------------------------------------
INSERT IGNORE INTO triz_kategorien (bereich, schluessel, name_de, name_ru, sortierung) VALUES
('video','grundlagen',   'Grundlagen TRIZ',          'Основы ТРИЗ',                 10),
('video','business-triz','Business TRIZ',            'Бизнес‑ТРИЗ',                 20),
('video','planung',      'Strategische Planung',     'Стратегическое планирование', 30),
('video','methoden',     'Innovationsmethoden',      'Методы инноваций',            40),
('video','fallstudien',  'Fallstudien',              'Кейсы',                       50),
('video','unternehmen',  'Unternehmensentwicklung',  'Развитие компании',           60),
('video','ki-triz',      'KI und TRIZ',              'ИИ и ТРИЗ',                   70);

-- ---------------------------------------------------------------------------
-- Nachrichtenquellen
--
-- Verwendet werden Feed-Adressen von Nachrichtensuchdiensten. Der Grund:
-- Ein Feed ist eine Zusage des Anbieters, dass diese Adresse maschinell
-- gelesen werden darf; eine Ergebnisseite automatisiert abzurufen ist bei
-- fast jedem Anbieter untersagt und bricht bei jeder Layoutänderung.
--
-- Fachportale mit eigenem Feed trägt ein Administrator zusätzlich ein - die
-- Adressen ändern sich zu oft, um sie hier festzuschreiben.
-- ---------------------------------------------------------------------------

-- Deutschsprachig
INSERT IGNORE INTO triz_quellen (art, name, url, sprache, region, kategorie_id) VALUES
('rss','TRIZ (DE)',
 'https://news.google.com/rss/search?q=TRIZ+Innovation&hl=de&gl=DE&ceid=DE:de','de','de',
 (SELECT id FROM triz_kategorien WHERE bereich='news' AND schluessel='business-triz')),
('rss','Business TRIZ (DE)',
 'https://news.google.com/rss/search?q=%22Business+TRIZ%22+OR+%22TRIZ+Methode%22&hl=de&gl=DE&ceid=DE:de','de','de',
 (SELECT id FROM triz_kategorien WHERE bereich='news' AND schluessel='business-triz')),
('rss','Innovationsmanagement (DE)',
 'https://news.google.com/rss/search?q=Innovationsmanagement&hl=de&gl=DE&ceid=DE:de','de','de',
 (SELECT id FROM triz_kategorien WHERE bereich='news' AND schluessel='innovation')),
('rss','Systemisches Denken (DE)',
 'https://news.google.com/rss/search?q=%22systemisches+Denken%22+Unternehmen&hl=de&gl=DE&ceid=DE:de','de','de',
 (SELECT id FROM triz_kategorien WHERE bereich='news' AND schluessel='systemdenken')),
('rss','Lean Management (DE)',
 'https://news.google.com/rss/search?q=Lean+Management+OR+Kaizen&hl=de&gl=DE&ceid=DE:de','de','de',
 (SELECT id FROM triz_kategorien WHERE bereich='news' AND schluessel='lean')),
('rss','Prozessoptimierung (DE)',
 'https://news.google.com/rss/search?q=Prozessoptimierung+Unternehmen&hl=de&gl=DE&ceid=DE:de','de','de',
 (SELECT id FROM triz_kategorien WHERE bereich='news' AND schluessel='prozesse')),
('rss','Strategisches Management (DE)',
 'https://news.google.com/rss/search?q=%22strategisches+Management%22+OR+Unternehmensstrategie&hl=de&gl=DE&ceid=DE:de','de','de',
 (SELECT id FROM triz_kategorien WHERE bereich='news' AND schluessel='strategie')),
('rss','Geschäftsmodellinnovation (DE)',
 'https://news.google.com/rss/search?q=Gesch%C3%A4ftsmodellinnovation+OR+%22neues+Gesch%C3%A4ftsmodell%22&hl=de&gl=DE&ceid=DE:de','de','de',
 (SELECT id FROM triz_kategorien WHERE bereich='news' AND schluessel='geschaeftsmodell')),
('rss','KI im Mittelstand (DE)',
 'https://news.google.com/rss/search?q=%22K%C3%BCnstliche+Intelligenz%22+Mittelstand+Innovation&hl=de&gl=DE&ceid=DE:de','de','de',
 (SELECT id FROM triz_kategorien WHERE bereich='news' AND schluessel='ki-triz')),
('rss','Elektrohandwerk und Digitalisierung (DE)',
 'https://news.google.com/rss/search?q=Elektrohandwerk+Digitalisierung+OR+Handwerk+Prozesse&hl=de&gl=DE&ceid=DE:de','de','de',
 (SELECT id FROM triz_kategorien WHERE bereich='news' AND schluessel='handwerk'));

-- Russischsprachig — Bereich 2 des Auftrags
INSERT IGNORE INTO triz_quellen (art, name, url, sprache, region, kategorie_id) VALUES
('rss','ТРИЗ (RU)',
 'https://news.google.com/rss/search?q=%D0%A2%D0%A0%D0%98%D0%97&hl=ru&gl=RU&ceid=RU:ru','ru','ru',
 (SELECT id FROM triz_kategorien WHERE bereich='news' AND schluessel='business-triz')),
('rss','Бизнес‑ТРИЗ (RU)',
 'https://news.google.com/rss/search?q=%22%D0%B1%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%A2%D0%A0%D0%98%D0%97%22&hl=ru&gl=RU&ceid=RU:ru','ru','ru',
 (SELECT id FROM triz_kategorien WHERE bereich='news' AND schluessel='business-triz')),
('rss','Теория решения изобретательских задач (RU)',
 'https://news.google.com/rss/search?q=%22%D1%82%D0%B5%D0%BE%D1%80%D0%B8%D1%8F+%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D1%8F+%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B5%D1%82%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D0%BA%D0%B8%D1%85+%D0%B7%D0%B0%D0%B4%D0%B0%D1%87%22&hl=ru&gl=RU&ceid=RU:ru','ru','ru',
 (SELECT id FROM triz_kategorien WHERE bereich='news' AND schluessel='business-triz')),
('rss','Альтшуллер (RU)',
 'https://news.google.com/rss/search?q=%D0%90%D0%BB%D1%8C%D1%82%D1%88%D1%83%D0%BB%D0%BB%D0%B5%D1%80+%D0%A2%D0%A0%D0%98%D0%97&hl=ru&gl=RU&ceid=RU:ru','ru','ru',
 (SELECT id FROM triz_kategorien WHERE bereich='news' AND schluessel='business-triz')),
('rss','Управление и инновации (RU)',
 'https://news.google.com/rss/search?q=%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5+%D0%B8%D0%BD%D0%BD%D0%BE%D0%B2%D0%B0%D1%86%D0%B8%D1%8F%D0%BC%D0%B8&hl=ru&gl=RU&ceid=RU:ru','ru','ru',
 (SELECT id FROM triz_kategorien WHERE bereich='news' AND schluessel='innovation')),
('rss','Системное мышление (RU)',
 'https://news.google.com/rss/search?q=%22%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%BD%D0%BE%D0%B5+%D0%BC%D1%8B%D1%88%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5%22&hl=ru&gl=RU&ceid=RU:ru','ru','ru',
 (SELECT id FROM triz_kategorien WHERE bereich='news' AND schluessel='systemdenken')),
('rss','Развитие бизнеса (RU)',
 'https://news.google.com/rss/search?q=%22%D1%80%D0%B0%D0%B7%D0%B2%D0%B8%D1%82%D0%B8%D0%B5+%D0%B1%D0%B8%D0%B7%D0%BD%D0%B5%D1%81%D0%B0%22+%D0%BC%D0%B5%D1%82%D0%BE%D0%B4&hl=ru&gl=RU&ceid=RU:ru','ru','ru',
 (SELECT id FROM triz_kategorien WHERE bereich='news' AND schluessel='unternehmen')),
('rss','ТРИЗ на производстве (RU)',
 'https://news.google.com/rss/search?q=%D0%A2%D0%A0%D0%98%D0%97+%D0%BF%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%BE&hl=ru&gl=RU&ceid=RU:ru','ru','ru',
 (SELECT id FROM triz_kategorien WHERE bereich='news' AND schluessel='produktion')),
('rss','Бережливое производство (RU)',
 'https://news.google.com/rss/search?q=%D0%B1%D0%B5%D1%80%D0%B5%D0%B6%D0%BB%D0%B8%D0%B2%D0%BE%D0%B5+%D0%BF%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%BE&hl=ru&gl=RU&ceid=RU:ru','ru','ru',
 (SELECT id FROM triz_kategorien WHERE bereich='news' AND schluessel='lean')),
('rss','ТРИЗ и ИИ (RU)',
 'https://news.google.com/rss/search?q=%D0%A2%D0%A0%D0%98%D0%97+%22%D0%B8%D1%81%D0%BA%D1%83%D1%81%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9+%D0%B8%D0%BD%D1%82%D0%B5%D0%BB%D0%BB%D0%B5%D0%BA%D1%82%22&hl=ru&gl=RU&ceid=RU:ru','ru','ru',
 (SELECT id FROM triz_kategorien WHERE bereich='news' AND schluessel='ki-triz')),
('rss','ТРИЗ — Bing News (RU)',
 'https://www.bing.com/news/search?q=%D0%A2%D0%A0%D0%98%D0%97+%D0%B1%D0%B8%D0%B7%D0%BD%D0%B5%D1%81&format=RSS','ru','ru',
 (SELECT id FROM triz_kategorien WHERE bereich='news' AND schluessel='business-triz'));

-- International
INSERT IGNORE INTO triz_quellen (art, name, url, sprache, region, kategorie_id) VALUES
('rss','TRIZ (EN)',
 'https://news.google.com/rss/search?q=TRIZ+%22inventive+problem+solving%22&hl=en-US&gl=US&ceid=US:en','en','int',
 (SELECT id FROM triz_kategorien WHERE bereich='news' AND schluessel='business-triz')),
('rss','Systematic Innovation (EN)',
 'https://news.google.com/rss/search?q=%22systematic+innovation%22+OR+%22innovation+management%22&hl=en-US&gl=US&ceid=US:en','en','int',
 (SELECT id FROM triz_kategorien WHERE bereich='news' AND schluessel='innovation')),
('rss','AI and Innovation Methods (EN)',
 'https://news.google.com/rss/search?q=TRIZ+%22artificial+intelligence%22&hl=en-US&gl=US&ceid=US:en','en','int',
 (SELECT id FROM triz_kategorien WHERE bereich='news' AND schluessel='ki-triz'));

-- ===========================================================================
-- Die 39 technischen Parameter
--
-- Grundlage der Widerspruchsmatrix: Ein technischer Widerspruch heißt, dass
-- die Verbesserung des einen Parameters einen anderen verschlechtert.
-- ===========================================================================
INSERT IGNORE INTO triz_bibliothek (art, nummer, titel_de, titel_ru, text_de, text_ru, beispiel_de, beispiel_ru, sortierung) VALUES
('parameter', 1,'Masse des beweglichen Objekts','Масса подвижного объекта','Gewicht eines Objekts, das sich im Schwerefeld bewegt.','Вес объекта, перемещающегося в поле тяжести.','','',1),
('parameter', 2,'Masse des unbeweglichen Objekts','Масса неподвижного объекта','Gewicht eines Objekts, das seinen Ort nicht wechselt.','Вес объекта, не меняющего своего положения.','','',2),
('parameter', 3,'Länge des beweglichen Objekts','Длина подвижного объекта','Jede lineare Abmessung eines bewegten Objekts.','Любой линейный размер подвижного объекта.','','',3),
('parameter', 4,'Länge des unbeweglichen Objekts','Длина неподвижного объекта','Jede lineare Abmessung eines ruhenden Objekts.','Любой линейный размер неподвижного объекта.','','',4),
('parameter', 5,'Fläche des beweglichen Objekts','Площадь подвижного объекта','Innere oder äußere Fläche eines bewegten Objekts.','Внутренняя или внешняя поверхность подвижного объекта.','','',5),
('parameter', 6,'Fläche des unbeweglichen Objekts','Площадь неподвижного объекта','Innere oder äußere Fläche eines ruhenden Objekts.','Внутренняя или внешняя поверхность неподвижного объекта.','','',6),
('parameter', 7,'Volumen des beweglichen Objekts','Объём подвижного объекта','Rauminhalt eines bewegten Objekts.','Объём подвижного объекта.','','',7),
('parameter', 8,'Volumen des unbeweglichen Objekts','Объём неподвижного объекта','Rauminhalt eines ruhenden Objekts.','Объём неподвижного объекта.','','',8),
('parameter', 9,'Geschwindigkeit','Скорость','Tempo eines Vorgangs oder einer Bewegung.','Темп процесса или движения.','','',9),
('parameter',10,'Kraft','Сила','Jede Einwirkung, die den Zustand eines Objekts ändert.','Любое воздействие, изменяющее состояние объекта.','','',10),
('parameter',11,'Spannung, Druck','Напряжение, давление','Innere Beanspruchung, Kraft je Fläche.','Внутреннее напряжение, сила на единицу площади.','','',11),
('parameter',12,'Form','Форма','Äußere Gestalt eines Systems.','Внешние очертания системы.','','',12),
('parameter',13,'Stabilität der Zusammensetzung','Стабильность состава объекта','Beständigkeit von Aufbau und Zusammenhalt.','Устойчивость состава и целостности объекта.','','',13),
('parameter',14,'Festigkeit','Прочность','Widerstand gegen Zerstörung.','Сопротивление разрушению.','','',14),
('parameter',15,'Wirkdauer des beweglichen Objekts','Время действия подвижного объекта','Zeit, die ein bewegtes Objekt seine Funktion erfüllt.','Время, в течение которого подвижный объект выполняет функцию.','','',15),
('parameter',16,'Wirkdauer des unbeweglichen Objekts','Время действия неподвижного объекта','Zeit, die ein ruhendes Objekt seine Funktion erfüllt.','Время, в течение которого неподвижный объект выполняет функцию.','','',16),
('parameter',17,'Temperatur','Температура','Wärmezustand eines Systems oder Teils.','Тепловое состояние системы или её части.','','',17),
('parameter',18,'Helligkeit','Освещённость','Lichtstärke, Sichtbarkeit, Beleuchtungsqualität.','Сила света, видимость, качество освещения.','','',18),
('parameter',19,'Energieverbrauch des beweglichen Objekts','Энергия, расходуемая подвижным объектом','Energie, die ein bewegtes Objekt aufnimmt.','Энергия, потребляемая подвижным объектом.','','',19),
('parameter',20,'Energieverbrauch des unbeweglichen Objekts','Энергия, расходуемая неподвижным объектом','Energie, die ein ruhendes Objekt aufnimmt.','Энергия, потребляемая неподвижным объектом.','','',20),
('parameter',21,'Leistung','Мощность','Arbeit je Zeiteinheit.','Работа в единицу времени.','','',21),
('parameter',22,'Energieverluste','Потери энергии','Energie, die nicht der Hauptfunktion zugutekommt.','Энергия, не идущая на выполнение главной функции.','','',22),
('parameter',23,'Stoffverluste','Потери вещества','Verlust an Material oder Substanz.','Потери материала или вещества.','','',23),
('parameter',24,'Informationsverluste','Потери информации','Verlorene oder nicht ankommende Information.','Утраченная или не дошедшая информация.','','',24),
('parameter',25,'Zeitverluste','Потери времени','Zeit, in der nichts Nützliches geschieht.','Время, в течение которого не выполняется полезное действие.','','',25),
('parameter',26,'Stoffmenge','Количество вещества','Menge des benötigten Materials.','Количество требуемого вещества.','','',26),
('parameter',27,'Zuverlässigkeit','Надёжность','Fähigkeit, die Funktion unter allen Bedingungen zu erfüllen.','Способность выполнять функцию во всех условиях.','','',27),
('parameter',28,'Messgenauigkeit','Точность измерения','Übereinstimmung von Messwert und Wirklichkeit.','Соответствие измеренного значения действительному.','','',28),
('parameter',29,'Fertigungsgenauigkeit','Точность изготовления','Übereinstimmung von Ergebnis und Vorgabe.','Соответствие результата заданным характеристикам.','','',29),
('parameter',30,'Schädliche Faktoren von außen','Вредные факторы, действующие извне','Störungen, die von außen auf das System wirken.','Воздействия, идущие на систему извне.','','',30),
('parameter',31,'Vom System erzeugte schädliche Faktoren','Вредные факторы, генерируемые объектом','Nebenwirkungen, die das System selbst hervorbringt.','Побочные эффекты, порождаемые самой системой.','','',31),
('parameter',32,'Fertigungsfreundlichkeit','Удобство изготовления','Aufwand, das System herzustellen.','Трудоёмкость изготовления системы.','','',32),
('parameter',33,'Bedienkomfort','Удобство эксплуатации','Aufwand für den, der das System benutzt.','Затраты усилий того, кто пользуется системой.','','',33),
('parameter',34,'Reparaturfreundlichkeit','Удобство ремонта','Aufwand, Fehler zu finden und zu beheben.','Трудоёмкость поиска и устранения неисправностей.','','',34),
('parameter',35,'Anpassungsfähigkeit','Адаптация, универсальность','Fähigkeit, auf veränderte Bedingungen zu reagieren.','Способность отвечать на изменившиеся условия.','','',35),
('parameter',36,'Komplexität der Struktur','Сложность устройства','Zahl und Verflechtung der Bestandteile.','Число и переплетение элементов.','','',36),
('parameter',37,'Komplexität der Kontrolle','Сложность контроля и измерения','Aufwand, den Zustand des Systems festzustellen.','Трудоёмкость определения состояния системы.','','',37),
('parameter',38,'Automatisierungsgrad','Степень автоматизации','Anteil der Arbeit, der ohne Menschen abläuft.','Доля работы, выполняемой без участия человека.','','',38),
('parameter',39,'Produktivität','Производительность','Zahl der Funktionen oder Ergebnisse je Zeiteinheit.','Число функций или результатов в единицу времени.','','',39);

-- ===========================================================================
-- Die 40 innovativen Prinzipien
--
-- Erläuterung und Beispiel sind auf Betrieb und Verwaltung gemünzt, nicht auf
-- Maschinenbau: Genau darin unterscheidet sich Business TRIZ von der
-- klassischen Anwendung.
-- ===========================================================================
INSERT IGNORE INTO triz_bibliothek (art, nummer, titel_de, titel_ru, text_de, text_ru, beispiel_de, beispiel_ru, sortierung) VALUES
('prinzip', 1,'Zerlegung','Дробление',
 'Ein Ganzes in unabhängige Teile zerlegen; ein Objekt leicht zerlegbar machen; den Grad der Zerlegung erhöhen.',
 'Разделить объект на независимые части; сделать объект разборным; увеличить степень дробления.',
 'Einen langen Auftrag in abrechenbare Teilleistungen schneiden – jede Stufe wird einzeln abgenommen und bezahlt, statt dass am Ende alles gleichzeitig strittig ist.',
 'Разделить крупный заказ на отдельные этапы: каждый принимается и оплачивается отдельно, вместо спора обо всём сразу в конце.',1),
('prinzip', 2,'Abtrennung','Вынесение',
 'Die störende Eigenschaft oder umgekehrt die einzig nötige Eigenschaft aus dem Ganzen herauslösen.',
 'Отделить от объекта мешающую часть или, наоборот, выделить единственно нужную часть.',
 'Die Angebotskalkulation aus dem Tagesgeschäft der Projektleitung herauslösen und in einer Rolle bündeln – die Störung durch Baustellenanrufe fällt weg.',
 'Вынести расчёт предложений из повседневной работы руководителя проекта в отдельную роль — помехи от звонков с объекта исчезают.',2),
('prinzip', 3,'Örtliche Qualität','Местное качество',
 'Von der gleichförmigen zur ungleichförmigen Struktur übergehen; jedem Teil die Eigenschaft geben, die genau dort gebraucht wird.',
 'Перейти от однородной структуры к неоднородной; каждой части придать свойство, нужное именно там.',
 'Nicht jede Baustelle bekommt dieselbe Dokumentationstiefe: Großprojekt mit vollem Berichtswesen, Kleinauftrag mit einem Formblatt.',
 'Не каждому объекту одинаковая глубина документации: крупный проект — полная отчётность, мелкий заказ — один бланк.',3),
('prinzip', 4,'Asymmetrie','Асимметрия',
 'Symmetrische Formen durch asymmetrische ersetzen; bestehende Asymmetrie verstärken.',
 'Перейти от симметричной формы к асимметричной; усилить уже имеющуюся асимметрию.',
 'Ungleiche Verteilung bewusst nutzen: der erfahrenste Monteur bekommt die schwierigen Anlagen, nicht den gleichen Anteil an allem.',
 'Осознанно использовать неравномерность: самому опытному монтажнику — сложные установки, а не равную долю всего.',4),
('prinzip', 5,'Kopplung','Объединение',
 'Gleichartige oder benachbarte Objekte räumlich zusammenlegen; Arbeitsgänge zeitlich zusammenlegen.',
 'Соединить однородные или смежные объекты; совместить операции во времени.',
 'Wartung, Prüfung und Kundengespräch in einem Termin bündeln statt drei Anfahrten.',
 'Объединить обслуживание, проверку и разговор с заказчиком в один визит вместо трёх выездов.',5),
('prinzip', 6,'Universalität','Универсальность',
 'Ein Objekt mehrere Funktionen erfüllen lassen, sodass andere entbehrlich werden.',
 'Объект выполняет несколько функций, благодаря чему отпадает надобность в других объектах.',
 'Das Aufmaßprotokoll dient zugleich als Abnahmeprotokoll und als Grundlage der Rechnung – ein Formular statt drei.',
 'Акт обмера служит одновременно актом приёмки и основанием для счёта — один бланк вместо трёх.',6),
('prinzip', 7,'Verschachtelung','«Матрёшка»',
 'Ein Objekt im Inneren eines anderen unterbringen, dieses wiederum in einem dritten.',
 'Один объект размещается внутри другого, который, в свою очередь, находится внутри третьего.',
 'Die Wochenmeldung steckt in der Projektakte, die Projektakte im Portfolio – jede Ebene enthält die nächste, ohne sie zu wiederholen.',
 'Недельный отчёт вложен в дело проекта, дело — в портфель: каждый уровень содержит следующий, не повторяя его.',7),
('prinzip', 8,'Gegengewicht','Антивес',
 'Das Gewicht eines Objekts durch Verbindung mit einem tragenden Objekt ausgleichen.',
 'Компенсировать вес объекта соединением с другим объектом, обладающим подъёмной силой.',
 'Ein verlustreiches Einstiegsangebot durch den anschließenden Wartungsvertrag ausgleichen.',
 'Убыточное входное предложение компенсировать последующим договором на обслуживание.',8),
('prinzip', 9,'Vorgezogene Gegenwirkung','Предварительное антидействие',
 'Vor der eigentlichen Wirkung eine Gegenwirkung aufbauen, die die spätere schädliche Nebenwirkung aufhebt.',
 'Заранее создать противодействие, снимающее будущее вредное воздействие.',
 'Vor Baubeginn den Bestand fotografisch dokumentieren – der spätere Streit über vorhandene Schäden entfällt.',
 'До начала работ зафиксировать существующее состояние на фото — спор о прежних повреждениях отпадает.',9),
('prinzip',10,'Vorgezogene Wirkung','Предварительное действие',
 'Die erforderliche Wirkung ganz oder teilweise im Voraus erzeugen; Objekte so bereitstellen, dass sie ohne Zeitverlust wirken können.',
 'Выполнить требуемое действие заранее полностью или частично; заранее расставить объекты так, чтобы они действовали без потери времени.',
 'Material am Vorabend kommissionieren und im Fahrzeug verladen – der Monteur startet ohne Lagergang.',
 'Скомплектовать материал накануне и загрузить в машину — монтажник начинает без захода на склад.',10),
('prinzip',11,'Vorbeugendes Polster','Заранее подложенная подушка',
 'Die geringe Zuverlässigkeit eines Systems durch vorbereitete Notmittel ausgleichen.',
 'Компенсировать невысокую надёжность объекта заранее подготовленными аварийными средствами.',
 'Ein Ersatzgerät im Servicefahrzeug: Fällt das Messgerät aus, geht der Tag trotzdem weiter.',
 'Запасной прибор в сервисной машине: при отказе измерителя день всё равно продолжается.',11),
('prinzip',12,'Äquipotenzialität','Эквипотенциальность',
 'Die Arbeitsbedingungen so ändern, dass ein Objekt nicht gehoben oder gesenkt werden muss.',
 'Изменить условия работы так, чтобы не требовалось поднимать или опускать объект.',
 'Freigaben auf der Ebene entscheiden, auf der sie entstehen – kein Hochreichen in die Geschäftsführung und Zurück.',
 'Решать согласования на том уровне, где они возникают, — без подъёма к руководству и обратно.',12),
('prinzip',13,'Umkehrung','Наоборот',
 'Statt der vorgeschriebenen Wirkung die entgegengesetzte ausführen; Bewegliches feststellen und Festes bewegen; das Objekt umdrehen.',
 'Вместо действия, диктуемого условиями, осуществить обратное; сделать подвижное неподвижным, а неподвижное подвижным; перевернуть объект.',
 'Nicht der Kunde bringt die Unterlagen ins Büro – der Sachbearbeiter erfasst sie auf der Baustelle mit dem Tablet.',
 'Не заказчик везёт документы в офис — сотрудник фиксирует их на объекте с планшета.',13),
('prinzip',14,'Kugelähnlichkeit','Сфероидальность',
 'Von geraden Linien zu krummen übergehen, von ebenen Flächen zu kugelförmigen; Rollen und Wirbel nutzen.',
 'Перейти от прямолинейных частей к криволинейным, от плоских поверхностей к сферическим; использовать ролики и вращение.',
 'Statt einer starren Karrierestufenleiter Rollenwechsel im Kreis: Jeder durchläuft Montage, Planung und Abnahme.',
 'Вместо жёсткой карьерной лестницы — смена ролей по кругу: каждый проходит монтаж, планирование и приёмку.',14),
('prinzip',15,'Dynamisierung','Динамичность',
 'Die Eigenschaften eines Systems so ändern, dass sie in jeder Phase optimal sind; ein starres Objekt beweglich machen; in bewegliche Teile zerlegen.',
 'Характеристики объекта должны меняться так, чтобы быть оптимальными на каждом этапе; сделать неподвижный объект подвижным; разделить на подвижные части.',
 'Die Teamgröße folgt dem Baufortschritt statt einer festen Besetzung über die gesamte Laufzeit.',
 'Численность бригады следует за ходом работ, а не фиксирована на весь срок.',15),
('prinzip',16,'Partielle oder überschüssige Wirkung','Частичное или избыточное действие',
 'Ist die volle Wirkung schwer erreichbar, etwas weniger oder etwas mehr tun – die Aufgabe wird dadurch wesentlich einfacher.',
 'Если трудно получить 100 % требуемого эффекта, надо получить чуть меньше или чуть больше — задача существенно упростится.',
 'Ein Angebot bewusst grob kalkulieren und mit klarem Vorbehalt versehen, statt tagelang auf eine Scheingenauigkeit hinzuarbeiten.',
 'Сознательно посчитать предложение укрупнённо с чёткой оговоркой вместо многодневной работы на мнимую точность.',16),
('prinzip',17,'Übergang in eine andere Dimension','Переход в другое измерение',
 'Von einer Linie zur Fläche, von der Fläche zum Raum; mehrstöckige Anordnung; Neigung; die Rückseite nutzen.',
 'Перейти от линии к плоскости, от плоскости к пространству; многоэтажная компоновка; наклон объекта; использование обратной стороны.',
 'Die Auftragsliste nicht als Reihe abarbeiten, sondern als Matrix aus Dringlichkeit und Deckungsbeitrag betrachten.',
 'Смотреть на список заказов не как на очередь, а как на матрицу срочности и маржинальности.',17),
('prinzip',18,'Mechanische Schwingungen','Механические колебания',
 'Ein Objekt in Schwingung versetzen; die Frequenz erhöhen; mit Resonanz arbeiten.',
 'Привести объект в колебательное движение; увеличить частоту; использовать резонанс.',
 'Kurze, feste Taktungen einführen: die tägliche Zehn-Minuten-Abstimmung wirkt stärker als die Monatsbesprechung.',
 'Ввести короткий устойчивый такт: ежедневная десятиминутка действует сильнее, чем ежемесячное совещание.',18),
('prinzip',19,'Periodische Wirkung','Периодическое действие',
 'Von der kontinuierlichen zur periodischen Wirkung übergehen; die Pausen für eine andere Wirkung nutzen.',
 'Перейти от непрерывного действия к периодическому; использовать паузы для другого действия.',
 'Bereitschaftsdienst statt Dauerbesetzung – die Pausen zwischen den Einsätzen dienen der Vorbereitung.',
 'Дежурство вместо постоянного присутствия: паузы между вызовами идут на подготовку.',19),
('prinzip',20,'Kontinuität der Wirkprozesse','Непрерывность полезного действия',
 'Ohne Leerlauf arbeiten; alle Teile ständig mit voller Last; Leerbewegungen beseitigen.',
 'Работать без холостого хода; все части объекта постоянно работают с полной нагрузкой; устранить холостые ходы.',
 'Rückfahrten des Servicefahrzeugs mit Materialrückläufen oder einem zweiten Termin belegen.',
 'Обратные рейсы сервисной машины загрузить возвратом материалов или вторым визитом.',20),
('prinzip',21,'Durcheilen','Проскок',
 'Einen Vorgang oder einzelne Stufen mit hoher Geschwindigkeit überwinden, wenn dort Schaden droht.',
 'Вести процесс или отдельные его этапы на большой скорости, если на них возникает вред.',
 'Die kritische Umschaltung in der Nacht in einem engen Zeitfenster durchziehen, statt sie über Tage zu strecken.',
 'Критическое переключение провести ночью в узком окне, а не растягивать на дни.',21),
('prinzip',22,'Schaden in Nutzen wandeln','Обратить вред в пользу',
 'Schädliche Faktoren zur Erzielung eines positiven Effekts nutzen; einen Schaden durch einen zweiten aufheben; ihn so weit verstärken, bis er aufhört, schädlich zu sein.',
 'Использовать вредные факторы для получения положительного эффекта; устранить вред сложением с другим вредом; усилить вред настолько, чтобы он перестал быть вредным.',
 'Reklamationen systematisch auswerten und als Vertriebsargument für die eigene Qualitätssicherung nutzen.',
 'Систематически разбирать рекламации и использовать это как аргумент продаж в пользу собственного контроля качества.',22),
('prinzip',23,'Rückkopplung','Обратная связь',
 'Eine Rückkopplung einführen; ist sie vorhanden, sie verändern.',
 'Ввести обратную связь; если она есть — изменить её.',
 'Der Monteur sieht am Tagesende den eigenen Fertigstellungsgrad gegen den Plan – nicht erst der Projektleiter im Monatsbericht.',
 'Монтажник видит свою степень готовности к плану в конце дня, а не руководитель проекта в месячном отчёте.',23),
('prinzip',24,'Vermittler','Посредник',
 'Ein Zwischenobjekt einsetzen, das die Wirkung überträgt; das Objekt zeitweilig mit einem leicht entfernbaren anderen verbinden.',
 'Использовать промежуточный объект, переносящий действие; на время присоединить к объекту другой, легко удаляемый объект.',
 'Ein neutraler Sachverständiger nimmt die strittige Leistung ab – die Beziehung zum Kunden bleibt unbelastet.',
 'Спорную работу принимает независимый эксперт — отношения с заказчиком остаются нетронутыми.',24),
('prinzip',25,'Selbstbedienung','Самообслуживание',
 'Das Objekt bedient sich selbst und führt Hilfs- und Reparaturfunktionen selbst aus; Abfälle nutzen.',
 'Объект должен сам себя обслуживать, выполняя вспомогательные и ремонтные операции; использовать отходы.',
 'Der Kunde erfasst Störmeldungen selbst im Portal – strukturiert, statt telefonisch nacherfragt zu werden.',
 'Заказчик сам заносит заявки о неисправностях в портал — структурированно, без переспрашивания по телефону.',25),
('prinzip',26,'Kopieren','Копирование',
 'Statt eines unzugänglichen, teuren oder empfindlichen Objekts eine vereinfachte Kopie nutzen; optische Kopien; Maßstabsänderung.',
 'Вместо недоступного, дорогого или хрупкого объекта использовать его упрощённую копию; оптические копии; изменение масштаба.',
 'Am digitalen Zwilling der Anlage schulen, statt Übungen an der laufenden Anlage zu fahren.',
 'Обучать на цифровом двойнике установки вместо упражнений на работающем оборудовании.',26),
('prinzip',27,'Billige Kurzlebigkeit statt teurer Langlebigkeit','Дешёвая недолговечность взамен дорогой долговечности',
 'Ein teures Objekt durch mehrere billige ersetzen und dabei auf einzelne Eigenschaften verzichten.',
 'Заменить дорогой объект набором дешёвых, поступившись некоторыми качествами.',
 'Für die Bauphase einfache Verbrauchswerkzeuge statt der teuren Ausstattung – der Verlust auf der Baustelle schmerzt dann nicht.',
 'На время стройки — простой расходный инструмент вместо дорогого: потеря на объекте не бьёт по карману.',27),
('prinzip',28,'Ersatz des mechanischen Systems','Замена механической схемы',
 'Ein mechanisches Wirkprinzip durch ein optisches, akustisches, thermisches oder elektromagnetisches ersetzen; Felder statt Kontakt.',
 'Заменить механическую схему оптической, акустической, тепловой или электромагнитной; использовать поля вместо контакта.',
 'Papierlaufmappen durch einen digitalen Freigabeweg ersetzen – kein physischer Transport von Unterschriften mehr.',
 'Заменить бумажные бегунки цифровым маршрутом согласования — физическая передача подписей исчезает.',28),
('prinzip',29,'Pneumo- und Hydrokonstruktionen','Использование пневмо- и гидроконструкций',
 'Statt fester Teile gasförmige oder flüssige nutzen: aufblasbar, hydrostatisch, hydroreaktiv.',
 'Вместо твёрдых частей использовать газообразные и жидкие: надувные, гидростатические, гидрореактивные.',
 'Puffer statt Starrheit: ein flexibler Personalpool fängt Auftragsspitzen ab, wo eine feste Besetzung bräche.',
 'Буфер вместо жёсткости: гибкий кадровый резерв гасит пики заказов там, где фиксированный штат ломается.',29),
('prinzip',30,'Biegsame Hüllen und dünne Folien','Использование гибких оболочек и тонких плёнок',
 'Statt massiver Konstruktionen biegsame Hüllen verwenden; ein Objekt mit einer dünnen Hülle von der Umgebung trennen.',
 'Вместо объёмных конструкций использовать гибкие оболочки и плёнки; изолировать объект от среды тонкой оболочкой.',
 'Eine dünne Regelschicht: ein einseitiges Merkblatt statt eines Handbuchs, das niemand liest.',
 'Тонкий слой регламента: односторонняя памятка вместо руководства, которое никто не читает.',30),
('prinzip',31,'Poröse Werkstoffe','Применение пористых материалов',
 'Ein Objekt porös machen oder poröse Elemente einfügen; die Poren mit einem Stoff füllen.',
 'Сделать объект пористым или ввести пористые элементы; заполнить поры веществом.',
 'Bewusste Lücken im Terminplan, in die Störungen hineinlaufen können, ohne die Kette zu reißen.',
 'Сознательные зазоры в графике, куда уходят сбои, не разрывая цепочку.',31),
('prinzip',32,'Farbveränderung','Изменение окраски',
 'Farbe oder Durchsichtigkeit eines Objekts oder seiner Umgebung ändern; Indikatoren und Markierungen einsetzen.',
 'Изменить окраску или степень прозрачности объекта либо среды; использовать индикаторы и метки.',
 'Ampelfarben im Projektdashboard: Der Status ist im Vorbeigehen erfassbar, ohne Zahlen zu lesen.',
 'Цвета светофора в панели проектов: статус считывается на ходу, без чтения цифр.',32),
('prinzip',33,'Gleichartigkeit','Однородность',
 'Objekte, die mit einem gegebenen Objekt zusammenwirken, aus demselben Material fertigen.',
 'Объекты, взаимодействующие с данным объектом, должны быть сделаны из того же материала.',
 'Nachunternehmer arbeiten mit denselben Formularen und Fristen wie die eigenen Teams – keine Übersetzungsschicht.',
 'Субподрядчики работают по тем же формам и срокам, что и свои бригады, — без прослойки перевода.',33),
('prinzip',34,'Beseitigung und Regenerierung von Teilen','Отброс и регенерация частей',
 'Einen Teil, der seine Aufgabe erfüllt hat, entfernen oder umwandeln; verbrauchte Teile im Betrieb wiederherstellen.',
 'Выполнившую своё назначение часть отбросить или видоизменить; расходуемые части восстанавливать по ходу работы.',
 'Projektorganisation nach Abschluss auflösen statt als Dauereinrichtung mitzuschleppen.',
 'Проектную организацию после завершения распускать, а не тащить как постоянную структуру.',34),
('prinzip',35,'Veränderung von Eigenschaften','Изменение физико-химических параметров объекта',
 'Aggregatzustand, Konzentration, Konsistenz, Flexibilität oder Temperatur ändern.',
 'Изменить агрегатное состояние, концентрацию, консистенцию, степень гибкости, температуру.',
 'Aus dem Festpreisvertrag einen Vertrag mit Preisgleitklausel machen – dieselbe Leistung, anderer Aggregatzustand des Risikos.',
 'Превратить договор с твёрдой ценой в договор со скользящей ценой — та же работа, другое агрегатное состояние риска.',35),
('prinzip',36,'Phasenübergang','Применение фазовых переходов',
 'Erscheinungen nutzen, die bei einem Phasenübergang auftreten: Volumenänderung, Wärmeabgabe oder -aufnahme.',
 'Использовать явления, возникающие при фазовых переходах: изменение объёма, выделение или поглощение тепла.',
 'Den Moment des Eigentumsübergangs bewusst gestalten: Mit der Abnahme ändert sich schlagartig, wer welches Risiko trägt.',
 'Осознанно оформить момент перехода: с приёмкой скачком меняется, кто какой риск несёт.',36),
('prinzip',37,'Wärmeausdehnung','Применение теплового расширения',
 'Ausdehnung oder Zusammenziehen von Stoffen bei Temperaturänderung nutzen; mehrere Stoffe mit verschiedenen Ausdehnungskoeffizienten kombinieren.',
 'Использовать расширение или сжатие материалов при изменении температуры; применять несколько материалов с разными коэффициентами расширения.',
 'Saisonale Spannungen einplanen: Kapazität im Sommer ausdehnen, im Winter zusammenziehen, statt ganzjährig zu mitteln.',
 'Планировать сезонные колебания: летом расширять мощности, зимой сжимать, вместо усреднения на весь год.',37),
('prinzip',38,'Starke Oxidationsmittel','Применение сильных окислителей',
 'Von normaler zu angereicherter Umgebung übergehen; die Wirkung durch ein stärkeres Mittel beschleunigen.',
 'Перейти от обычной среды к обогащённой; ускорить процесс более сильным средством.',
 'Für einen begrenzten Zeitraum eine deutlich stärkere Ressource einsetzen – externe Fachkraft für die kritische Phase.',
 'На ограниченный срок ввести заметно более сильный ресурс — внешнего специалиста на критический этап.',38),
('prinzip',39,'Träges Milieu','Применение инертной среды',
 'Das normale Milieu durch ein neutrales ersetzen; den Vorgang im Vakuum durchführen; neutrale Zusätze einbringen.',
 'Заменить обычную среду нейтральной; вести процесс в вакууме; вводить нейтральные добавки.',
 'Ideenrunden ohne Anwesenheit von Vorgesetzten: Ohne Hierarchie im Raum entstehen andere Vorschläge.',
 'Сессии идей без присутствия руководителей: без иерархии в комнате рождаются другие предложения.',39),
('prinzip',40,'Verbundwerkstoffe','Применение композиционных материалов',
 'Von gleichartigen zu zusammengesetzten Materialien übergehen, die die Vorzüge mehrerer verbinden.',
 'Перейти от однородных материалов к композиционным, соединяющим достоинства нескольких.',
 'Gemischte Teams aus Meister, Techniker und Kaufmann statt rein fachlicher Besetzung – der Auftrag wird von allen Seiten gesehen.',
 'Смешанные команды из мастера, техника и коммерсанта вместо чисто отраслевого состава: заказ виден со всех сторон.',40);

-- ===========================================================================
-- Die acht Entwicklungsgesetze technischer Systeme
-- ===========================================================================
INSERT IGNORE INTO triz_bibliothek (art, nummer, titel_de, titel_ru, text_de, text_ru, beispiel_de, beispiel_ru, sortierung) VALUES
('trend',1,'Vollständigkeit der Teile','Полнота частей системы',
 'Ein lebensfähiges System braucht vier Teile: Antrieb, Übertragung, Werkzeug und Steuerung. Fehlt eines, arbeitet das System nur mit fremder Hilfe.',
 'Жизнеспособная система требует четырёх частей: двигателя, трансмиссии, рабочего органа и органа управления. Без одной из них система работает лишь с чужой помощью.',
 'Ein Verbesserungswesen ohne Steuerung: Ideen werden gesammelt, aber niemand entscheidet – das System läuft nicht an.',
 'Система улучшений без органа управления: идеи собираются, но никто не решает — система не запускается.',1),
('trend',2,'Energiedurchgängigkeit','Энергетическая проводимость системы',
 'Ein System funktioniert nur, wenn Energie – im Betrieb: Information und Entscheidungsbefugnis – ungehindert durch alle Teile fließt.',
 'Система работоспособна, если энергия — в организации это информация и полномочия — беспрепятственно проходит через все её части.',
 'Wenn jede Entscheidung über drei Ebenen läuft, versickert die Energie unterwegs.',
 'Если каждое решение проходит через три уровня, энергия рассеивается по пути.',2),
('trend',3,'Abstimmung der Rhythmik','Согласование ритмики частей системы',
 'Die Takte der Teile müssen aufeinander abgestimmt sein. Unabgestimmte Rhythmen erzeugen Warteschlangen und Leerlauf.',
 'Ритмика частей системы должна быть согласована. Несогласованные ритмы порождают очереди и простои.',
 'Wöchentliche Materialbestellung bei täglichem Baufortschritt – die Baustelle wartet regelmäßig einen halben Tag.',
 'Еженедельный заказ материалов при ежедневном ходе работ: объект регулярно ждёт полдня.',3),
('trend',4,'Erhöhung des Idealitätsgrades','Увеличение степени идеальности',
 'Systeme entwickeln sich in Richtung des idealen Endresultats: Der Nutzen wächst, Aufwand und Schaden gehen gegen null. Im Grenzfall gibt es das System nicht mehr, seine Funktion aber sehr wohl.',
 'Системы развиваются в сторону идеального конечного результата: полезность растёт, затраты и вред стремятся к нулю. В пределе системы нет, а функция выполняется.',
 'Die beste Rechnungsprüfung ist die, die entfällt, weil die Daten schon bei der Erfassung stimmen.',
 'Лучшая проверка счетов — та, которой нет, потому что данные верны уже при вводе.',4),
('trend',5,'Ungleichmäßige Entwicklung der Teile','Неравномерность развития частей системы',
 'Teile eines Systems entwickeln sich unterschiedlich schnell. Der am weitesten zurückliegende Teil begrenzt das Ganze und ist die eigentliche Aufgabe.',
 'Части системы развиваются неравномерно. Наиболее отставшая часть ограничивает целое и составляет действительную задачу.',
 'Modernes Planungswerkzeug, aber Aufmaß auf Papier: Der Engpass ist nicht die Software.',
 'Современный инструмент планирования при обмерах на бумаге: узкое место — не программа.',5),
('trend',6,'Übergang ins Obersystem','Переход в надсистему',
 'Hat ein System seine Möglichkeiten ausgeschöpft, wird es Teil eines übergeordneten Systems; die Weiterentwicklung läuft dann dort.',
 'Исчерпав свои возможности, система входит в надсистему как её часть; дальнейшее развитие идёт на уровне надсистемы.',
 'Das Einzelunternehmen stößt an Grenzen und geht in einen Verbund, der Einkauf und Ausbildung gemeinsam trägt.',
 'Отдельная фирма упирается в предел и входит в объединение, которое совместно ведёт закупки и обучение.',6),
('trend',7,'Übergang vom Makro- zum Mikroniveau','Переход с макроуровня на микроуровень',
 'Die Wirkung wandert von groben, mechanischen Mitteln zu feineren Ebenen.',
 'Действие переходит от грубых механических средств к более тонким уровням.',
 'Von der Jahresplanung über die Wochensteuerung zur ereignisgesteuerten Reaktion in Stunden.',
 'От годового планирования через недельное управление к реакции по событиям в часах.',7),
('trend',8,'Erhöhung der Stoff-Feld-Wechselwirkung','Увеличение степени вепольности',
 'Systeme entwickeln sich zu vollständigeren, besser steuerbaren Wirkungsgefügen aus Stoffen und Feldern.',
 'Системы развиваются в сторону более полных и лучше управляемых вепольных структур.',
 'Aus der mündlichen Anweisung wird eine Regel, aus der Regel ein Formular, aus dem Formular eine Prüfung im System.',
 'Из устного указания рождается правило, из правила — бланк, из бланка — проверка в системе.',8);

-- ===========================================================================
-- Business-TRIZ-Methoden
-- ===========================================================================
INSERT IGNORE INTO triz_bibliothek (art, nummer, titel_de, titel_ru, text_de, text_ru, beispiel_de, beispiel_ru, sortierung) VALUES
('methode',1,'Ideales Endresultat (IER)','Идеальный конечный результат (ИКР)',
 'Beschreibt das Ergebnis, als gäbe es keine Beschränkungen: Die Funktion erfüllt sich von selbst, ohne Aufwand und ohne Schaden. Das IER wird nie erreicht – es zeigt die Richtung und deckt auf, welche der angeblichen Beschränkungen echt sind.',
 'Описывает результат так, будто ограничений нет: функция выполняется сама собой, без затрат и вреда. ИКР недостижим — он задаёт направление и вскрывает, какие из мнимых ограничений настоящие.',
 'IER für die Baustellendokumentation: „Die Dokumentation entsteht von selbst, während gearbeitet wird."',
 'ИКР для документации на объекте: «Документация возникает сама собой в ходе работы».',1),
('methode',2,'Technischer Widerspruch','Техническое противоречие',
 'Zwei Anforderungen an dasselbe System stehen gegeneinander: Die Verbesserung des einen Parameters verschlechtert einen anderen. Der Weg führt über die Widerspruchsmatrix zu den passenden Prinzipien – nicht über den Kompromiss.',
 'Два требования к одной системе противостоят друг другу: улучшение одного параметра ухудшает другой. Путь идёт через матрицу противоречий к приёмам, а не через компромисс.',
 'Mehr Prüfschritte erhöhen die Qualität (27) und verlängern die Bearbeitungszeit (25).',
 'Больше проверок повышает надёжность (27) и увеличивает время (25).',2),
('methode',3,'Physikalischer Widerspruch','Физическое противоречие',
 'Ein und dieselbe Eigenschaft muss gleichzeitig vorhanden und abwesend sein. Aufgelöst wird das durch Trennung in Zeit, Raum, Bedingung oder Systemebene.',
 'Одно и то же свойство должно одновременно быть и отсутствовать. Разрешается разделением во времени, в пространстве, по условию или по уровню системы.',
 'Das Angebot muss verbindlich sein (für den Kunden) und unverbindlich (für uns) – Trennung nach Bedingung: verbindlich bis zur Bemusterung, danach Anpassung.',
 'Предложение должно быть обязывающим (для заказчика) и необязывающим (для нас) — разделение по условию: обязывает до согласования образцов, далее корректируется.',3),
('methode',4,'Funktionsanalyse','Функциональный анализ',
 'Zerlegt ein System in Komponenten und beschreibt, welche Komponente auf welche wie wirkt: nützlich, unzureichend, überschüssig oder schädlich. Die Analyse zeigt, wo Wert entsteht und wo nur Aufwand.',
 'Разделяет систему на компоненты и описывает, какой компонент как воздействует на другой: полезно, недостаточно, избыточно или вредно. Анализ показывает, где создаётся ценность, а где только затраты.',
 'Analyse des Angebotsprozesses: Von elf Beteiligten wirken drei unzureichend, zwei doppelt.',
 'Анализ процесса подготовки предложений: из одиннадцати участников трое действуют недостаточно, двое — дублируя друг друга.',4),
('methode',5,'Trimming (Reduzieren)','Свёртывание',
 'Entfernt eine Komponente und verteilt ihre nützliche Funktion auf die verbleibenden. Die Leitfrage lautet nicht „Wie verbessern wir es?", sondern „Warum brauchen wir es überhaupt?".',
 'Убирает компонент, передавая его полезную функцию оставшимся. Ведущий вопрос не «как улучшить?», а «зачем это вообще нужно?».',
 'Die Zwischenkontrolle entfällt, weil die Erfassung selbst die Prüfung enthält.',
 'Промежуточный контроль отпадает, поскольку сама фиксация содержит проверку.',5),
('methode',6,'Ressourcenanalyse','Анализ ресурсов',
 'Sucht vor jeder neuen Investition nach dem, was bereits da ist: Stoffe, Felder, Raum, Zeit, Information, Menschen, Abfälle. Die beste Lösung nutzt vorhandene Ressourcen und kostet damit nichts.',
 'Перед любыми новыми вложениями ищет то, что уже есть: вещества, поля, пространство, время, информацию, людей, отходы. Лучшее решение использует имеющиеся ресурсы и потому ничего не стоит.',
 'Die Wartezeit des Monteurs vor Ort ist eine Zeitressource: Sie trägt die Dokumentation des Vortags.',
 'Время ожидания монтажника на объекте — ресурс времени: оно вмещает документацию за прошлый день.',6),
('methode',7,'Ursache-Wirkungs-Kettenanalyse','Причинно-следственный анализ',
 'Verfolgt einen Nachteil rückwärts über alle Zwischenursachen bis zu den Schlüsselnachteilen. Diese sind die Ansatzpunkte; alles davor ist Symptombehandlung.',
 'Прослеживает недостаток назад через все промежуточные причины до ключевых. Именно они — точки приложения усилий; всё, что ближе к поверхности, — лечение симптомов.',
 'Verzögerte Rechnung ← fehlendes Aufmaß ← kein Termin beim Kunden ← Terminvergabe nicht Teil der Abnahme.',
 'Задержка счёта ← нет акта обмера ← нет визита к заказчику ← назначение визита не входит в приёмку.',7),
('methode',8,'Stoff-Feld-Analyse (Vepol)','Вепольный анализ',
 'Modelliert jede Wirkung als Dreieck aus zwei Stoffen und einem Feld. Fehlt ein Element oder ist die Wirkung schädlich, geben die Standardlösungen die Umbauwege vor.',
 'Моделирует любое действие как треугольник из двух веществ и поля. Если элемента нет или действие вредно, стандартные решения задают способы перестройки.',
 'Anweisung ohne Rückmeldekanal: Das Feld fehlt – ein Vepol lässt sich erst mit einer Rückmeldung schließen.',
 'Указание без канала обратной связи: поля нет — веполь замыкается только с обратной связью.',8),
('methode',9,'Systemoperator (Neun Fenster)','Системный оператор («девять экранов»)',
 'Betrachtet die Aufgabe gleichzeitig auf drei Systemebenen (Teilsystem, System, Obersystem) und in drei Zeiten (Vergangenheit, Gegenwart, Zukunft). Neun Blickwinkel statt einem.',
 'Рассматривает задачу одновременно на трёх уровнях (подсистема, система, надсистема) и в трёх временах (прошлое, настоящее, будущее). Девять точек зрения вместо одной.',
 'Der Fachkräftemangel sieht im Obersystem (Branche, Ausbildung) anders aus als im Teilsystem (einzelne Kolonne).',
 'Нехватка кадров в надсистеме (отрасль, обучение) выглядит иначе, чем в подсистеме (отдельная бригада).',9),
('methode',10,'Methode der kleinen Männchen','Метод маленьких человечков',
 'Ersetzt das strittige Teil gedanklich durch eine Menge kleiner Akteure, die sich anders verhalten dürfen als ein starres Ganzes. Löst festgefahrene physikalische Widersprüche.',
 'Заменяет спорный элемент множеством маленьких деятелей, которым позволено вести себя иначе, чем жёсткому целому. Разрешает застрявшие физические противоречия.',
 'Statt „die Abteilung" die einzelnen Vorgänge betrachten – manche dürfen warten, andere nicht.',
 'Вместо «отдела» рассмотреть отдельные операции: одни могут ждать, другие — нет.',10),
('methode',11,'S-Kurven-Analyse','Анализ S‑кривой',
 'Ordnet ein Produkt, einen Prozess oder ein Geschäftsmodell in seinen Lebenszyklus ein: Entstehung, Wachstum, Reife, Verfall. Jede Phase verlangt andere Werkzeuge – in der Reife bringt Optimierung nichts mehr.',
 'Помещает продукт, процесс или бизнес‑модель в жизненный цикл: зарождение, рост, зрелость, спад. Каждая фаза требует своих инструментов — в зрелости оптимизация уже не даёт отдачи.',
 'Klassische Elektroinstallation in der Reife, Gebäudeautomation im Wachstum: unterschiedliche Investitionslogik.',
 'Классический электромонтаж в зрелости, автоматизация зданий в росте: разная логика вложений.',11),
('methode',12,'Hauptparameter des Werts (MPV)','Главные параметры ценности (MPV)',
 'Bestimmt, woran der Kunde den Wert tatsächlich misst – und trennt das von dem, was der Anbieter für wichtig hält. Verbesserungen außerhalb der MPV kosten Geld und bringen nichts.',
 'Определяет, по чему заказчик на самом деле измеряет ценность, отделяя это от того, что важным считает поставщик. Улучшения вне MPV стоят денег и не дают ничего.',
 'Für den Bauherrn zählt der eingehaltene Termin mehr als die letzte Ziffer im Preis.',
 'Для застройщика соблюдённый срок значит больше, чем последняя цифра в цене.',12);

-- ===========================================================================
-- Innovations- und Management-Werkzeuge
-- ===========================================================================
INSERT IGNORE INTO triz_bibliothek (art, nummer, titel_de, titel_ru, text_de, text_ru, beispiel_de, beispiel_ru, sortierung) VALUES
('werkzeug',1,'Business Model Canvas','Канва бизнес‑модели',
 'Neun Felder, die ein Geschäftsmodell auf einer Seite zeigen: Kundensegmente, Wertversprechen, Kanäle, Beziehungen, Erlöse, Ressourcen, Aktivitäten, Partner, Kosten. Gut geeignet, um vor der TRIZ-Analyse den Rahmen abzustecken.',
 'Девять полей, показывающих бизнес‑модель на одной странице: сегменты, ценностное предложение, каналы, отношения, доходы, ресурсы, деятельность, партнёры, издержки. Хорош, чтобы очертить рамку до анализа по ТРИЗ.',
 '','',1),
('werkzeug',2,'Jobs to be Done','Работа, которую нанимают выполнить',
 'Fragt nicht, was der Kunde kauft, sondern welche Aufgabe er damit erledigt. Deckt Wettbewerber auf, die man nicht als solche sieht, und passt eng zur MPV-Analyse.',
 'Спрашивает не что заказчик покупает, а какую работу он этим выполняет. Вскрывает конкурентов, которых не считают конкурентами, и тесно смыкается с анализом MPV.',
 '','',2),
('werkzeug',3,'Wertstromanalyse','Карта потока создания ценности',
 'Bildet einen Prozess vom Auslöser bis zum Ergebnis ab und trennt wertschöpfende von wartenden Zeitanteilen. Meist liegt der Anteil echter Wertschöpfung unter einem Zehntel der Durchlaufzeit.',
 'Отображает процесс от запуска до результата и разделяет время создания ценности и время ожидания. Как правило, доля настоящей ценности — меньше десятой части времени цикла.',
 '','',3),
('werkzeug',4,'Fünfmal Warum','Пять «почему»',
 'Fragt sich vom Symptom zur Ursache durch. Einfach und wirksam, aber linear – wo mehrere Ursachen zusammenwirken, ist die Ursache-Wirkungs-Kettenanalyse das schärfere Werkzeug.',
 'Продвигается вопросами от симптома к причине. Просто и действенно, но линейно: там, где причин несколько, причинно‑следственный анализ точнее.',
 '','',4),
('werkzeug',5,'Ishikawa-Diagramm','Диаграмма Исикавы',
 'Sortiert mögliche Ursachen nach Mensch, Maschine, Material, Methode, Milieu und Messung. Sammelt breit, bevor die Kettenanalyse in die Tiefe geht.',
 'Раскладывает возможные причины по категориям: человек, машина, материал, метод, среда, измерение. Собирает вширь до того, как анализ уйдёт вглубь.',
 '','',5),
('werkzeug',6,'PDCA','Цикл PDCA',
 'Planen, Umsetzen, Prüfen, Anpassen – der Grundtakt jeder Verbesserung. Ohne den Prüfschritt bleibt jede Maßnahme eine Behauptung.',
 'Планируй, делай, проверяй, корректируй — базовый такт любого улучшения. Без шага проверки любая мера остаётся утверждением.',
 '','',6),
('werkzeug',7,'Kanban','Канбан',
 'Macht laufende Arbeit sichtbar und begrenzt sie. Wirkt vor allem gegen den häufigsten Fehler: zu viel gleichzeitig anzufangen.',
 'Делает текущую работу видимой и ограничивает её. Действует прежде всего против самой частой ошибки — начинать слишком много одновременно.',
 '','',7),
('werkzeug',8,'OKR','OKR',
 'Verbindet wenige Ziele mit messbaren Schlüsselergebnissen für einen festen Zeitraum. Nützlich, um TRIZ-Ergebnisse in verbindliche Vorhaben zu überführen.',
 'Связывает немногие цели с измеримыми ключевыми результатами на заданный период. Полезен, чтобы перевести результаты ТРИЗ в обязывающие планы.',
 '','',8),
('werkzeug',9,'Szenariotechnik','Сценарное планирование',
 'Entwickelt mehrere plausible Zukünfte statt einer Prognose und prüft Vorhaben gegen jede davon. Ergänzt die S-Kurven-Analyse um äußere Entwicklungen.',
 'Разрабатывает несколько правдоподобных вариантов будущего вместо одного прогноза и проверяет замыслы по каждому. Дополняет анализ S‑кривой внешними факторами.',
 '','',9),
('werkzeug',10,'Blue-Ocean-Strategie','Стратегия голубого океана',
 'Sucht Märkte ohne direkten Wettbewerb, indem Merkmale gestrichen, reduziert, gesteigert oder neu geschaffen werden. Das Streichen deckt sich mit dem Trimming aus TRIZ.',
 'Ищет рынки без прямой конкуренции, упраздняя, снижая, повышая или создавая характеристики. Упразднение совпадает со свёртыванием в ТРИЗ.',
 '','',10);

-- ===========================================================================
-- Praxisbeispiele
--
-- Illustrationen aus dem Elektrohandwerk allgemein, keine Vorgänge der
-- elektromas GmbH. Eigene Fallstudien gehören in die Wissensdatenbank unter
-- „Fallstudien" - dort stehen sie mit Namen und Zahlen.
-- ===========================================================================
INSERT IGNORE INTO triz_bibliothek (art, nummer, titel_de, titel_ru, text_de, text_ru, beispiel_de, beispiel_ru, sortierung) VALUES
('beispiel',1,'Rüstzeit in der Vorfertigung','Время переналадки в предпроизводстве',
 'Widerspruch: Vorgefertigte Baugruppen verkürzen die Montagezeit (25), verlängern aber die Rüstzeit in der Werkstatt (25 an anderer Stelle) und binden Fläche (6).',
 'Противоречие: сборка узлов заранее сокращает время монтажа (25), но удлиняет переналадку в цехе и занимает площадь (6).',
 'Ansatz über Prinzip 10 (Vorgezogene Wirkung) und 5 (Kopplung): gleichartige Baugruppen mehrerer Aufträge in einem Rüstvorgang fertigen, Reihenfolge nach Montagetermin.',
 'Подход через приёмы 10 (предварительное действие) и 5 (объединение): однотипные узлы нескольких заказов изготавливать за одну наладку, порядок — по срокам монтажа.',1),
('beispiel',2,'Dokumentation auf der Baustelle','Документация на объекте',
 'Widerspruch: Vollständige Dokumentation erhöht die Nachweissicherheit (27), kostet aber Zeit des Monteurs (25).',
 'Противоречие: полная документация повышает доказательную надёжность (27), но отнимает время монтажника (25).',
 'Ansatz über Prinzip 25 (Selbstbedienung) und 4 des IER: Das Foto mit Zeitstempel ist gleichzeitig Fortschrittsmeldung, Aufmaßbeleg und Abnahmegrundlage – die Dokumentation entsteht bei der Arbeit statt danach.',
 'Подход через приём 25 (самообслуживание) и ИКР: фото с отметкой времени одновременно является отчётом о ходе работ, подтверждением обмера и основанием приёмки — документация возникает по ходу работы, а не после неё.',2),
('beispiel',3,'Notdienst außerhalb der Geschäftszeit','Аварийная служба вне рабочего времени',
 'Widerspruch: Erreichbarkeit rund um die Uhr bindet Personal (20) und ist ein starkes Verkaufsargument (39).',
 'Противоречие: круглосуточная доступность связывает персонал (20) и одновременно является сильным аргументом продаж (39).',
 'Ansatz über Prinzip 19 (Periodische Wirkung) und 24 (Vermittler): Bereitschaft im Wechsel mit einem Partnerbetrieb, gemeinsame Rufnummer – volle Abdeckung bei halber Bindung.',
 'Подход через приёмы 19 (периодическое действие) и 24 (посредник): дежурство по очереди с партнёрской фирмой, общий номер — полное покрытие при половинной нагрузке.',3),
('beispiel',4,'Nachträge und Kundenbeziehung','Дополнительные работы и отношения с заказчиком',
 'Widerspruch: Nachträge sichern die Marge (39), belasten aber das Verhältnis zum Auftraggeber (schädlicher Faktor 31).',
 'Противоречие: дополнительные работы удерживают маржу (39), но обременяют отношения с заказчиком (вредный фактор 31).',
 'Ansatz über Prinzip 9 (Vorgezogene Gegenwirkung) und 23 (Rückkopplung): Änderungsanzeige am selben Tag mit Preisfolge, unterschrieben vor der Ausführung – der Nachtrag ist dann keine Nachricht mehr, sondern eine Entscheidung des Kunden.',
 'Подход через приёмы 9 (предварительное антидействие) и 23 (обратная связь): уведомление об изменении в тот же день с ценой, подписанное до выполнения — тогда допработа не новость, а решение самого заказчика.',4),
('beispiel',5,'Einarbeitung neuer Mitarbeitender','Введение новых сотрудников в работу',
 'Widerspruch: Gründliche Einarbeitung bindet erfahrene Kräfte (20), oberflächliche erzeugt Fehler und Nacharbeit (31).',
 'Противоречие: основательное введение занимает опытных работников (20), поверхностное порождает ошибки и переделки (31).',
 'Ansatz über Prinzip 26 (Kopieren) und 2 (Abtrennung): typische Fälle einmal filmen und in den Schulungsbereich stellen; der erfahrene Monteur wird nur noch für das Ungewöhnliche gebraucht.',
 'Подход через приёмы 26 (копирование) и 2 (вынесение): типовые случаи снять один раз и поместить в учебный раздел; опытный монтажник нужен только для необычного.',5);
